### ISSUE TITLE
Complete example of golangci with custom messages

### ISSUE THREAD

**Issue by rynowak** [ashanbrown/forbidigo#30]
Hi, Thanks for working on this project. I've found it really useful so far.

I've been struggling to get custom messages working inside `golangci.yaml`. I've tried to a few different things and I'm wondering if you could point me at a complete example.

I've also found that mistakes in authoring the rules lead to a rule no-op'ing (because they are regexes).

Here's what I have tried so far.

**Starting From:**

```yaml
# see https://golangci-lint.run/usage/configuration/ for documentation
linters:
  enable:
  - forbidigo
linters-settings:
  forbidigo:
    # Forbid the following identifiers (list of regexp)
    forbid:
      # These APIs exit the process. These are OK to use in the main() function,
      # and not ANYWHERE else.
      - 'os\.Exit(#Do not use os.Exit except from the main() function. Suppress this warning inside the main() function with //nolint:forbidigo on the same line as the code.)'
      - 'log.Fatal(f|ln)?'
```

This has the desired effect. I want to add custom messages to these.

**Failed Attempt 1**

Using inline YAML like the README

```
# see https://golangci-lint.run/usage/configuration/ for documentation
linters:
  enable:
  - forbidigo
linters-settings:
  forbidigo:
    # Forbid the following identifiers (list of regexp)
    forbid:
      # These APIs exit the process. These are OK to use in the main() function,
      # and not ANYWHERE else.
      - |
        pattern: 'os\.Exit'
        msg: 'Do not use os.Exit except from the main() function. Suppress this warning inside the main() function with //nolint:forbidigo on the same line as the code.)'

      - 'log.Fatal(f|ln)?'
```

**Failed Attempt 2**

Using an embedded comment like this PR https://github.com/ashanbrown/forbidigo/pull/11

```
# see https://golangci-lint.run/usage/configuration/ for documentation
linters:
  enable:
  - forbidigo
linters-settings:
  forbidigo:
    # Forbid the following identifiers (list of regexp)
    forbid:
      # These APIs exit the process. These are OK to use in the main() function,
      # and not ANYWHERE else.
      - 'os\.Exit(#Do not use os.Exit except from the main() function. Suppress this warning inside the main() function with //nolint:forbidigo on the same line as the code.)'
      - 'log.Fatal(f|ln)?'
```
