### ISSUE TITLE
How to write method checks under third-party packages

### ISSUE THREAD

**Issue by demoManito** [ashanbrown/forbidigo#31]
```yaml
linters-settings:
  goimports:
    local-prefixes: github.com/MiaoSiLa
  forbidigo:
    forbid:
	  - 'github\.com\/jinzhu\/gorm\.Open(# do not used gorm.Open)?'
```
writing code as above didn't show any linter errors

@ashanbrown
