### ISSUE TITLE
Match method call

### ISSUE THREAD

**Issue by arxeiss** [ashanbrown/forbidigo#39]
Is there a way how to match only method call and not every identifier with the same name?

We have code like this below. On Identifier structure we define `ID` function, which we should use always. And `GID` which is more like a helper, which we can use only in Tests, so it can `panic` easily.

I wanted to use forbidigo to match all usage of `GID()` outside `*_test.go` files, but I wasn't successful. 

```go
const GID = "gid:"

type URIGidIdentifier struct {
	GID string `uri:"gid" binding:"required,gid"`
}

type Identifier struct {
    // ...
}

func (x *Identifier) GID() string {
	gid, err := x.ID()
	if err != nil {
		panic("use ID() to check error")
	}
	return gid
}

func (x *Identifier) ID() (string, error) {
    // ...
    return "", nil
}

func xx() {
    a := (&Identifier{}).GID() // this is only point, where forbidigo should complain.
}
```

## First try

I'm using GolangCI linter and if I added this, it was complaining about `GID` constant and `GID` field in `URIGidIdentifier` too. And also during GID() declaration.

```yaml
    forbidigo:
        forbid:
            - p: ^GID$
              msg: Use ID() instead
```

## Second try

I tried to check the function call like this, having escaped `()` in the regex, but now it is matching nothing. Nor false positives as above, nor valid ocurrences.

```yaml
    forbidigo:
        forbid:
            - p: ^GID\(\)$
              msg: Use ID() instead
```

Is there a way how to make this works?
