### ISSUE TITLE
Issue with forbidigo rule matching `!= Foo.Bar`

### ISSUE THREAD

**Issue by BorisLepage** [ashanbrown/forbidigo#54]
I am trying to use the forbidigo linter to enforce the rule that checks for occurrences of `!= Foo.Bar`.
However, when I attempt to match this pattern, I am encountering an issue.

Here is the rule I am trying to implement in the forbidigo configuration:

```yml
forbidigo:
  forbid:
    - p: \!\=\s*Foo\.Bar
      msg: Do not use '!= Foo.Bar'
```

In some cases, the use of `Foo.Bar` is legitimate, and I want to avoid catching false positives. That’s why I need to target != Foo.Bar, as I really want to catch the lines where `Foo.Bar` is used in a condition.

I would appreciate guidance.
