### ISSUE TITLE
Forbid specific imports

### ISSUE THREAD

**Issue by miparnisari** [ashanbrown/forbidigo#62]
I want to forbid people from importing a certain library. I couldn't find in the README or in https://golangci-lint.run/usage/linters/#forbidigo an example of how to do this.

I used

```
    forbidigo:
      forbid:
        - pattern: ^slices\.Filter
          pkg: ^k8s.io/utils/strings/slices$
          msg: "use github.com/samber/lo instead of k8s.io/utils/strings/slices"
      analyze_types: true
````

But this doesn't report anything.
